### ISSUE TITLE
US-23 Student Can Offer a Bribe to their Instructor

### ISSUE THREAD

**Issue by rfpcmaia** [soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-#114]
**USER STORY DESCRIPTION** 

**As a** student, **I want** to be able to bribe my professor, **so that** I can conveniently negotiate a better grade.

**TASK BREAKDOWN**

- [x] #115
- [x] #116
- [x] #117
- [x] #118

**USER ACCEPTANCE FLOW**

1. Student selects button "Bribe Instructor" in their homepage.
2. Student inputs a bribe amount they're willing to offer and the desired grade they want for that amount.
3. Students selects "Send bribe" and gets a confirmation that bribe was sent and to await professor response.

**ACCEPTANCE CRITERIA**

- [x] User acceptance flow is respected.
- [x] Student can offer a bribe to their student through their main page.
- [ ] Student may specify bribe amount and the grade they'd like for that amount.

**ACCEPTANCE TESTS**

- [ ] #119
