### ISSUE TITLE
US-24 Instructor can Accept, Refuse, or Counter Bribe

### ISSUE THREAD

**Issue by rfpcmaia** [soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-#120]
**USER STORY DESCRIPTION** 

**As an** instructor, **I want** to be able to view any bribe offers, **so that** I can accept, refuse, or counter them.

**TASK BREAKDOWN**

- [x] #121
- [x] #122
- [x] #123
- [x] #124
- [x] #125
- [x] #126
- [x] #127
- [x] #128
- [x] #129

**USER ACCEPTANCE FLOW**

1. Instructor gets a notification that they received a bribe offer.
2. Instructor can select "View Bribes" in their homepage to view any received bribes.
3. Instructor can "Accept" bribe, "Refuse" bribe, or "Counter" bribe.
4. If instructor accepts bribe, student gets a notification and their peer review scores are changed accordingly.
5. If instructor refuses bribe, student gets a notification and bribe is erased from records.
6. If instructor counters bribe, they can input a counter offer and select "Send offer".
7. Student is notified of any counter offers and may accept or refuse them.
8. If counter offer is refused, instructor is notified and bribe is erased from the system.
9. If counter offer is accepted, instructor is notified and the student's peer review scores are changed accordingly.

**ACCEPTANCE CRITERIA**

- [x] User acceptance flow is respected.
- [x] Instructor may view any bribe offers and either accept, refuse, or counter them.
- [x] Student is notified of the instructor's response.
- [x] Student may accept or refuse any counter offers.
- [x] If a bribe is agreed upon, instructor can see that the student's peer review scores have been changed automatically.

**ACCEPTANCE TESTS**

- [x] #130
