### ISSUE TITLE
US-16 Import Student List and Create Teams

### ISSUE THREAD

**Issue by rfpcmaia** [soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-#18]
**USER STORY DESCRIPTION** 

**As an** instructor, **I want** to upload the list of students in the course, **so that** I can create teams and assign students to them.

**TASK BREAKDOWN**

- [ ] #35
- [ ] #36
- [ ] #37
- [ ] #38
- [ ] #39
- [ ] #40

**USER ACCEPTANCE FLOW**

1. Instructor logs in and is presented with an option to upload course roaster.
2. Instructor clicks to upload and is given the option to upload a csv file containing the course roaster.
3. The file is uploaded and the course roaster is processed into the system's database.
4. Instructor is presented with an option to "Create Team".
5. Instructor selects the option to create teams and is taken to a new page for assigning teams.
7. Instructor is able to create a new team by giving it a name and assigning members to it from a list of students that have not yet been assigned to a team.
8. Once students are assigned to the team, instructor can click to "Create Team". 
9. Instructor is redirected to their homepage.
10. Instructor can select to "Create Team" again from the list of remaining students without a team.

**ACCEPTANCE CRITERIA**

- [ ] User acceptance flow is respected.
- [ ] Instructor is able to upload course roaster into the system.
- [ ] Instructor can create teams and assign students to them.

**ACCEPTANCE TESTS**

- [ ] #41
- [ ] #42
