### ISSUE TITLE
US-17 Select and Evaluate Teammates on a Five-Point Scale

### ISSUE THREAD

**Issue by rfpcmaia** [soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-#22]
**USER STORY DESCRIPTION**

**As a** student, **I want** to be able to rate each of my teammates on a 5-point scale on their level of Cooperation, **so that** I submit an evaluation of their contribution on that category.

**TASK BREAKDOWN**

- [x] #44
- [x] #45
- [x] #46
- [ ] #47
- [ ] #48

**USER ACCEPTANCE FLOW**

1. Student logs in and sees an option to evaluate their teammates, redirecting them to a new page.
2. Display a list of the student's teammates with a 5-point scale next to each one.
3. Students rates each of their teammates individually using the provided 5-point scale.
4. Student clicks to submit evaluation.
5. System redirects to student's homepage.

**ACCEPTANCE CRITERIA**

- [ ] Acceptance Flow is respected.
- [ ] Students can choose to rate their teammates.
- [ ] Using a 5-point scale, students can rate each of their teammates on the level of their Cooperation.

**ACCEPTANCE TEST**

- [ ] #43
